# compare data quality


Exp_Atlas <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/RAW/GEOD42968.txt",fill=T, header=T)
GSE42968 <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/GSE42968.txt", header=T)
GSE42968.Rsubread <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/GSE42968.Rsubread.txt")
dim(Exp_Atlas)
dim(GSE42968)
dim(GSE42968.Rsubread)

library(plyr)

ls <- list(GSE42968, Exp_Atlas, GSE42968.Rsubread)
mer <- join_all(ls, by = "Gene")
mer <- mer[complete.cases(mer),]

# SRR634969 - WTRep1, SRR634970 -WTrep2, SRR634971 - WTrep3
# SRR634972 - BPRep1

head(mer)
plot(x= log(mer[,2]), y = log(mer[, 11]), xlab= "BPrep1", ylab="SRR634972", pch=20)

cor(mer[, 5], mer[, 8], method="spearman")
cor(mer[, 6], mer[, 9], method="spearman")
cor(mer[, 7], mer[, 10], method="spearman")
cor(mer[, 2], mer[, 11], method="spearman")
cor(mer[, 3], mer[, 12], method="spearman")
cor(mer[, 4], mer[, 13], method="spearman")


cor(mer[,8], mer[,14], method="spearman")
cor(mer[,9], mer[,15], method="spearman")
cor(mer[,10], mer[,16], method="spearman")
cor(mer[,11], mer[,17], method="spearman")
cor(mer[,12], mer[,18], method="spearman")
cor(mer[,13], mer[,19], method="spearman")



head(mer[, c(5, 8, 14)], 10)

plot(x=log(mer[, 8]), y = log(mer[, 14]), pch=20)




#  this shows that data generated by Rsubread are very close to Atlas

GSE35288.Atlas <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/RAW/GEOD35288.txt",fill=T, header=T)
GSE35288.Rsubread <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/GSE35288.Rsubread.txt",fill=T, header=T)
GSE35288.Rsubread <- data.frame(Gene = row.names(GSE35288.Rsubread), GSE35288.Rsubread)

mer2 <- merge(GSE35288.Atlas, GSE35288.Rsubread, by="Gene")
dim(mer2)

nsamp <- dim(GSE35288.Atlas)[2]-1
r.pearson <- r.spearman <- rep(0, nsamp)
coe1 <- coe2 <-  rep(0, nsamp)

for ( i in 1 :nsamp)
{
  x <- mer2[, i + 1]
  y <- mer2[, i + 1 + nsamp]
  
  r.pearson[i] <- cor(x, y)
  r.spearman[i] <- cor(x, y, method="spearman") 
  l <- lm(y~x)
  coe1[i] <- as.numeric(l$coefficients[2]) # slope
  coe2[i] <- as.numeric(l$coefficients[1])
  # slope ranging from 1.56 to 1.84
    
}


plot(x=log(mer2[, 2]), y = log(mer2[, 2 + nsamp]), pch=20)


# what about count table from NCBI?
GSE53952 <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/GSE53952.txt",fill=T, header=T)
GSE53952.Rsubread <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/RAW/GSE53952_6sample.Rsubread.txt",fill=T, header=T)
GSE53952.Rsubread <- data.frame(Gene=row.names(GSE53952.Rsubread), GSE53952.Rsubread)

mer3 <- merge(GSE53952[, 1:7], GSE53952.Rsubread, by="Gene")

nsamp <- dim(GSE53952.Rsubread)[2]-1
r.pearson <- r.spearman <- rep(0, nsamp)
coe1 <- coe2 <-  rep(0, nsamp)

for ( i in 1 :nsamp)
{
  x <- mer3[, i + 1]
  y <- mer3[, i + 1 + nsamp]
  
  r.pearson[i] <- cor(x, y)
  r.spearman[i] <- cor(x, y, method="spearman") 
  l <- lm(y~x)
  coe1[i] <- as.numeric(l$coefficients[2]) # slope
  coe2[i] <- as.numeric(l$coefficients[1])
  # slope ranging from 1.05 to 1.06
  
}


colSums(mer3[, -1])


# Data I proceeded using Natural Protocol (Anders)

GSE48767 <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/GSE48767.txt",fill=T, header=T)
GSE48767 <- data.frame(GSE48767[, c(1, 5,6,7)], GSE48767[, 2:4])
GSE48767.Rsubread <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/GSE48767.Rsubread.txt",fill=T, header=T)
GSE48767.Rsubread <- data.frame(Gene=row.names(GSE48767.Rsubread), GSE48767.Rsubread)

mer4 <- merge(GSE48767, GSE48767.Rsubread[, -(2:7)], by="Gene")
head(mer4[, c(2, 8)])

nsamp <- dim(GSE48767.Rsubread)[2]-1
r.pearson <- r.spearman <- rep(0, nsamp)
coe1 <- coe2 <-  rep(0, nsamp)

for ( i in 1 :nsamp)
{
  x <- mer4[, i + 1]
  y <- mer4[, i + 1 + nsamp]
  
  r.pearson[i] <- cor(x, y)
  r.spearman[i] <- cor(x, y, method="spearman") 
  l <- lm(y~x)
  coe1[i] <- as.numeric(l$coefficients[2]) # slope
  coe2[i] <- as.numeric(l$coefficients[1])
  # slope ranging from 1.05 to 1.06
  
}

colSums(mer4[, -1])


plot(x=log(mer3[, 2]), y = log(mer3[, 2 + nsamp]), pch=20)



GSE37159 <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/GSE37159.txt",fill=T, header=T)
GSE37159.Rsubread <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/GSE37159.Rsubread.txt",fill=T, header=T)





GSE53078 <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/GSE53078.txt",fill=T, header=T)
GSE53078$Gene <- substr(GSE53078$Gene, 1, 9)
GSE53078.Rsubread <- read.table("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/GSE53078.Rsubread.txt",fill=T, header=T)
GSE53078.Rsubread <- data.frame(Gene=row.names(GSE53078.Rsubread), GSE53078.Rsubread)

mer5 <- merge(GSE53078, GSE53078.Rsubread, by="Gene")
head(mer5[, c(2, 6)])

nsamp <- dim(GSE53078.Rsubread)[2]-1
r.pearson <- r.spearman <- rep(0, nsamp)
coe1 <- coe2 <-  rep(0, nsamp)

for ( i in 1 :nsamp)
{
  x <- mer5[, i + 1]
  y <- mer5[, i + 1 + nsamp]
  
  r.pearson[i] <- cor(x, y)
  r.spearman[i] <- cor(x, y, method="spearman") 
  l <- lm(y~x)
  coe1[i] <- as.numeric(l$coefficients[2]) # slope
  coe2[i] <- as.numeric(l$coefficients[1])
  # slope ranging from 1.05 to 1.06
  
}

colSums(mer5[, -1])



compareData <- function(dat1, dat2)
{ 
  mer <- merge(dat1, dat2, by ="Gene")
  
  nsamp <- dim(dat2)[2]-1
  
  r.pearson <- r.spearman <- rep(0, nsamp)
  coe1 <- coe2 <-  rep(0, nsamp)
  
  for ( i in 1 :nsamp)
  {
    x <- mer[, i + 1]
    y <- mer[, i + 1 + nsamp]
    
    r.pearson[i] <- cor(x, y)
    r.spearman[i] <- cor(x, y, method="spearman") 
    l <- lm(y~x)
    coe1[i] <- as.numeric(l$coefficients[2]) # slope
    coe2[i] <- as.numeric(l$coefficients[1])
    # slope ranging from 1.05 to 1.06
    
  }
  
  ret.list <- list(mergeData= mer, r.pear= r.pearson, 
                   r.spear = r.spearman, intercept=coe2, slope=coe1)
  
  return(ret.list)
}


dat.name <- "GSE39214"

dat1.path <- paste("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/",
                   dat.name, ".txt", sep="")
dat1 <- read.table(dat1.path, fill=T, header=T)[, -1]

dat2.path <- paste("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/",
                   dat.name, ".Rsubread.txt", sep="")

dat2 <- read.table(dat2.path, fill=T, header=T)
dat2 <- data.frame(Gene=row.names(dat2), dat2)

xx <- compareData(dat1,dat2)


dat.name <- "GSE51772"

dat1.path <- paste("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/GSE/",
                   dat.name, ".txt", sep="")

dat1 <- read.table(dat1.path, fill=T, header=T)
head(dat1)

dat2.path <- paste("/Users/Bin/Dropbox/Zhuo/Research/Project2014/Data/arab/Rsubread/",
                   dat.name, ".Rsubread.txt", sep="")

dat2 <- read.table(dat2.path, fill=T, header=T)
dat2 <- data.frame(Gene=row.names(dat2), dat2)
head(dat2)
xx <- compareData(dat1,dat2)



